import time

word = [
["I could say I never dare", 0.1],
["To think about you in that way, but", 0.1],
["I would be lyin'", 0.1],
["And I pretend I'm happy for you"],
["When you find some dude to take home"],
["But I won't deny that"],
["In the midst of the crowds"],
["In the shapes in the clouds"],
["I don't see nobody but you"],
["In my rose-tinted dreams"],
["Wrinkled silk on my sheets"],
["I don't see nobody but you"],
["Boy, you got me hooked onto something"],
["Who could say that they saw us coming?"],
["Tell me"],
["Do you feel the love?"],
["Spend a summer or a lifetime with me"],
["Let me take you to the place of your dreams"],
["Tell me"],
["Do you feel the love?"],
["And I could say I never unzipped"],
["Those blue Levi's inside my head"],
["But that's far from the truth"],
["Don't know what's come over me"],
["It seems like yesterday when I said"],
["\"We\'ll be friends forever\""],
["Constellations of stars"],
["Murals on city walls"],
["I don't see nobody but you"],
["You're my vice, you're my muse"],
["You're a nineteenth floor view"],
["I don't see nobody but you"],
["Boy, you got me hooked onto something"],
["Who could say that they saw us coming?"],
["Tell me"],
["Do you feel the love?"],
["Spend a summer or a lifetime with me"],
["Let me take you to the place of your dreams"],
["Tell me"],
["Do you feel the love?"],
["Boy, you got me hooked onto something"],
["Who could say that they saw us coming?"],
["Tell me"],
["Do you feel the love?"],
["Spend a summer or a lifetime with me"],
["Let me take you to the place of your dreams"],
["Tell me"],
["Do you feel the love?"],
["Do you feel the love?"],
["Do you feel the love?"],
["Do you feel the love?"],
["Do you feel the love?"],
["Do you feel the love?"],
["Do you feel the love?"],
["Feel the love"],
["Do you feel the love?"]
]

for words in word:
    for char in words[0]:
        print(char, end="", flush=True)
        time.sleep(0.03)
    print("")